---
AWSTemplateFormatVersion: 2010-09-09
Description: >
    Creates resources for AWS Batch.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "AWS Batch Environment Config"
        Parameters:
        - VpcId
        - SubnetIds
        - SpotBidPercentage
        - DefaultCEMinvCpus
        - DefaultCEMaxvCpus
        - BatchServiceRoleArn
        - Ec2InstanceProfileArn
        - SpotFleetRoleArn
    ParameterLabels:
      VpcId:
        default: VPC ID
      SubnetIds:
        default: VPC Subnet IDs
      SpotBidPercentage:
        default: Spot market bid percentage (default = 100)
      DefaultCEMinvCpus:
        default: Default Queue Min vCPU count
      DefaultCEMaxvCpus:
        default: Default Queue Max vCPU count
      BatchServiceRoleArn:
        default: AWS Batch service role ARN
      Ec2InstanceProfileArn:
        default: EC2 Instance Profile ARN
      SpotFleetRoleArn:
        default: Spot Fleet Role ARN

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: 'The VPC to create security groups and deploy AWS Batch to. NOTE: Must be the same VPC as the provided subnet IDs.'
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: 'Subnets you want your batch compute environment to launch in. NOTE: Must be from the VPC provided.'
  SpotBidPercentage:
    Type: Number
    Description: Maximum Spot bid percentage from on-demand instance price.
    MaxValue: 100
    MinValue: 5
    Default: 100
  DefaultCEMinvCpus:
    Type: Number
    Description: Minimum number of CPUs in the default compute environment. Default 0 (i.e. no active instances if no jobs).
    Default: 4
    MinValue: 0
  DefaultCEMaxvCpus:
    Type: Number
    Description: Maximum number of CPUs in the default compute environment. Should be >= than MinCpus
    Default: 64
    MinValue: 0
  BatchServiceRoleArn:
    Type: String
    Description: The IAM Role ARN for the Batch service
  SpotFleetRoleArn:
    Type: String
    Description: The IAM Role ARN for Batch to call Spot Fleet service
  Ec2InstanceProfileArn:
    Type: String
    Description: The IAM Role ARN for instances launched by Batch

Resources:
  BatchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG for Batch
      VpcId:
        Ref: VpcId

  SGSSHIngress:
    Type: AWS::EC2::SecurityGroupIngress
    DependsOn: BatchSecurityGroup
    Properties:
      GroupId: !Ref BatchSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: 0.0.0.0/0

  SGAllTcpEgress:
    Type: AWS::EC2::SecurityGroupEgress
    DependsOn: BatchSecurityGroup
    Properties:
      GroupId: !Ref BatchSecurityGroup
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      CidrIp: 0.0.0.0/0

  SGAllTcpSelfIngress:
    Type: AWS::EC2::SecurityGroupIngress
    DependsOn: BatchSecurityGroup
    Properties:
      GroupId: !Ref BatchSecurityGroup
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId: !Ref BatchSecurityGroup
  
  WPS201VcfFilterJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName: wps201_vcf_filter
      ContainerProperties:
        Image: 'oddhypothesis/bcftools:1.9-aws'
        Vcpus: 2
        Memory: 4096
  
  WPS201FeatureFilterJobDefinition:
    Type: AWS::Batch::JobDefinition
    Properties:
      Type: container
      JobDefinitionName: wps201_feature_filter
      ContainerProperties:
        Image: 'oddhypothesis/allel:latest'
        Vcpus: 2
        Memory: 4096

  DefaultComputeEnv:
    Type: AWS::Batch::ComputeEnvironment
    DependsOn: BatchSecurityGroup
    Properties:
      ServiceRole: !Ref BatchServiceRoleArn
      Type: MANAGED
      State: ENABLED
      ComputeResources:
        BidPercentage: !Ref SpotBidPercentage
        InstanceRole: !Ref Ec2InstanceProfileArn
        InstanceTypes:
          - optimal
        MinvCpus: !Ref DefaultCEMinvCpus
        MaxvCpus: !Ref DefaultCEMaxvCpus
        SecurityGroupIds:
          - !Ref BatchSecurityGroup
        SpotIamFleetRole: !Ref SpotFleetRoleArn
        Subnets: !Ref SubnetIds
        Type: SPOT

  DefaultQueue:
    Type: AWS::Batch::JobQueue
    Properties:
      Priority: 1
      State: ENABLED
      ComputeEnvironmentOrder:
        - Order: 1
          ComputeEnvironment: !Ref DefaultComputeEnv

Outputs:
  DefaultJobQueueArn:
    Value: !Ref DefaultQueue
  WPS201VcfFilterJobDefinitionArn:
    Value: !Ref WPS201VcfFilterJobDefinition
  WPS201FeatureFilterJobDefinitionArn:
    Value: !Ref WPS201FeatureFilterJobDefinition
...