---
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Creates an S3 Bucket

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain

Outputs:
  BucketName:
    Value: !Ref S3Bucket
...