---
AWSTemplateFormatVersion: '2010-09-09'
Description: "re:Invent 2018 Builder Session WPS201"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterLabels:
      VpcId:
        default: VPC ID
      SubnetIds:
        default: VPC Subnet IDs
      SpotBidPercentage:
        default: Spot Bid %
      DefaultCEMinvCpus:
        default: Default Min vCPU
      DefaultCEMaxvCpus:
        default: Default Max vCPU

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: 'The VPC to create security groups and deploy AWS Batch to. NOTE: Must be the same VPC as the provided subnet IDs.'
  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: 'Subnets you want your batch compute environment to launch in. We recommend private subnets. NOTE: Must be from the VPC provided.'
  SpotBidPercentage:
    Description: The percent of on-demand pricing for max bid for Spot intances
    Type: Number
    Default: 100
  DefaultCEMinvCpus:
    Description: The minimum number of CPUs for the default Batch Compute Environment
    Type: Number
    Default: 0
  DefaultCEMaxvCpus:
    Description: The maximum number of CPUs for the default Batch Compute Environment
    Type: Number
    Default: 100

Resources:
  S3Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://reinvent-2018-wps201.s3.amazonaws.com/templates/s3.template.yaml
      TimeoutInMinutes: 5

  IamStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: S3Stack
    Properties:
      TemplateURL: https://reinvent-2018-wps201.s3.amazonaws.com/templates/iam.template.yaml
      TimeoutInMinutes: 10
      Parameters:
        S3BucketName: !Sub ${S3Stack.Outputs.BucketName}

  BatchStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - IamStack
    Properties:
      TemplateURL: https://reinvent-2018-wps201.s3.amazonaws.com/templates/batch.template.yaml
      TimeoutInMinutes: 10
      Parameters:
        VpcId: !Ref VpcId
        SubnetIds: !Join [",", !Ref SubnetIds ]
        SpotBidPercentage: !Ref SpotBidPercentage
        DefaultCEMinvCpus: !Ref DefaultCEMinvCpus
        DefaultCEMaxvCpus: !Ref DefaultCEMaxvCpus
        BatchServiceRoleArn: !Sub ${IamStack.Outputs.BatchServiceRoleArn}
        Ec2InstanceProfileArn: !Sub ${IamStack.Outputs.BatchInstanceProfileArn}
        SpotFleetRoleArn: !Sub ${IamStack.Outputs.BatchSpotFleetRoleArn}

  SageMakerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - S3Stack
      - IamStack
      - BatchStack
    Properties:
      TemplateURL: https://reinvent-2018-wps201.s3.amazonaws.com/templates/sagemaker.template.yaml
      TimeoutInMinutes: 10
      Parameters:
        S3Bucket: !Sub ${S3Stack.Outputs.BucketName}
        SageMakerExecutionRoleArn: !Sub ${IamStack.Outputs.SageMakerExecutionRoleArn}
        BatchJobQueueArn: !Sub ${BatchStack.Outputs.DefaultJobQueueArn}

Outputs:
  S3Bucket:
    Value: !Sub ${S3Stack.Outputs.BucketName}
    Export:
        Name: !Sub "${AWS::StackName}-S3Bucket"
  BatchJobQueueArn:
    Value: !Sub ${BatchStack.Outputs.DefaultJobQueueArn}
    Export:
        Name: !Sub "${AWS::StackName}-BatchJobQueueArn"
  SageMakerNotebookInstance:
    Value: !Sub ${SageMakerStack.Outputs.SageMakerNotebookInstance}
    Export:
        Name: !Sub "${AWS::StackName}-SageMakerNotebookInstance"