site_name: "re:Invent 2018 - WPS201"
theme: cinder

site_author: W. Lee Pang <pwyming@amazon.com>
copyright: 2018 Amazon Web Services

repo_url: https://github.com/wleepang/reinvent-2018-wps201
edit_uri: ""

markdown_extensions:
- admonition

extra_css:
- css/extra.css

nav:
- Home: index.md